import type { NextPage } from 'next'
import Head from 'next/head'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome" ;
import {faThumbsUp} from  "@fortawesome/free-regular-svg-icons";

const Home: NextPage = () => {
  return (
    
    <div className="flex-container justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
      <div className="justify-center">
        <h1 className='text-center'>Deegle</h1>

        <div className='flex justify-center'>

          <div className='m-24'>
            <div className=''>
              <textarea className='flex border-2 w-auto  h-40 border-rose-500 rounded-lg'></textarea>
            </div>
            <div className='pt-6'>
              <textarea className='border-2 w-auto  h-40 border-rose-500 rounded-lg '></textarea>
            </div>
          </div>
          
          <div className='m-24 '>
              <div className='flex space-x-96 '>
                <textarea className='border-2 w-auto  h-40 border-violet-700 rounded-lg '></textarea>
              </div>
              <div className='pt-6'>
                <textarea className='border-2	w-auto 	h-40 border-violet-700 rounded-lg '></textarea>
              </div>
          </div>
        </div>
        <FontAwesomeIcon icon={faThumbsUp} />
        <FontAwesomeIcon icon={faThumbsUp} />
      </div>
      </main>
      
      <footer className="">
      </footer>
    </div>
  )
}

export default Home
