import type { NextPage } from 'next'
import Head from 'next/head'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome" ;
import {faThumbsUp} from  "@fortawesome/free-regular-svg-icons";
import { SetStateAction, useState } from 'react';

const Home: NextPage = () => {

  //state初期値(入力用)
  const initialValue : any = "";

  //利用者がGoogle翻訳を使用して変換する際の値
  const [googleText,ConvertWithGoogle] = useState<string>(initialValue);

  //利用者がdeepleを使用して変換する際の値
  const [deeplText,ConvertWithDeepl] = useState<string>(initialValue);

    //利用者がGoogle翻訳を使用して変換した後の値
  const [aftTranGoogle,effectGoogle] = useState<string>(initialValue);

     //利用者がDeepl翻訳を使用して変換した後の値
  const [aftTranDeepl,effectDeepl] = useState<string>(initialValue);
 
  // e: { target: { value: string; }; }

  //入力値の状態に合わせて、翻訳後のtextareに反映する
  //イベント引数の型
  const TranslateGoogle = (e: { target: { value: string; }; }) => {
//e.target.valueで値取得
    ConvertWithGoogle(e.target.value);
    effectGoogle(e.target.value);
    }

  const TranslateDeeple = (e: { target: { value: string; }; }) => {
    //e.target.valueで値取得
    ConvertWithDeepl(e.target.value);
    effectDeepl(e.target.value);
  }
  
  const GoodGoogle = () => {
    console.log('Google翻訳を高く評価しました。');
  }
  const GoodDeeple = () => {
    console.log('Deppleを高く評価しました。');
  }

  return (
    
    <div className="flex-container justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
      <div className="justify-center">
        <h1 className='text-center'>Deegle</h1>

        <div className='flex justify-center'>

          <div className='m-24'>
            <div className=''>
              <textarea id="userInputGoogleText" onChange={TranslateGoogle} className='flex border-2 w-auto  h-40 border-rose-500 rounded-lg' value={googleText}></textarea>
            </div>
            <div className='pt-6'>
              <textarea id="" className=' flex border-2 w-auto  h-40 border-rose-500 rounded-lg ' value={aftTranGoogle}></textarea>
            </div>
            <button className='fa-2x' onClick={GoodGoogle}><FontAwesomeIcon icon={faThumbsUp} className="w-48" color='red'/></button>
          </div>
          
          <div className='m-24 '>
              <div className='flex space-x-96 '>
                <textarea id="userInputText" onChange={TranslateDeeple} className='border-2 w-auto  h-40 border-violet-700 rounded-lg' value={deeplText}></textarea>
              </div>
              <div className='pt-6'>
                <textarea id="" className=' flex border-2	w-auto 	h-40 border-violet-700 rounded-lg' value={aftTranDeepl}>
                </textarea>
              </div>
              <button className='fa-2x' onClick={GoodDeeple}><FontAwesomeIcon icon={faThumbsUp} className="flex w-48"  color='red'/></button>
        
          </div>
        </div>
      </div>
      </main>
      
      <footer className="">
      </footer>
    </div>
  )
}
export default Home
