import type { NextPage } from 'next'
import Head from 'next/head'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome" ;
import {faThumbsUp} from  "@fortawesome/free-regular-svg-icons";
import  {useState}  from 'react';
import ConvertWithGoogle, { UserTranslationText } from './components/UserTranslationText';
import Header from './components/Header';



const Home: NextPage = () => {

  // state初期値(入力用)
  const initialValue : any = "";
  // 利用者がしたいテキストの値
  const [inputText, userText] = useState<any>(initialValue);
  // 利用者がGoogle翻訳を使用して変換した後の値
  const [aftTranGoogle, setAftTranGoogle] = useState<any>(initialValue);
  // 利用者がDeepl翻訳を使用して変換した後の値
  const [aftTranDeepl, setAftTranDeepl] = useState<any>(initialValue);
 
  // 入力値の状態に合わせて、翻訳後のtextareに反映する
  // e: { target: { value: string; }; }
  const translate = (e : any) : void => {
    // e.target.valueで値取得
    userText(e.target.value);
    setAftTranGoogle(e.target.value);
    setAftTranDeepl(e.target.value);
  };

  // Googleのいいね機能
  const goodGoogle = () => {
    console.log('Google翻訳を高く評価しました。');
  };

  // deeplのいいね機能
  const goodDeeple = () => {
    console.log('DeepLを高く評価しました。');
  };

  return (
    <div className="flex-container justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header/>
      <main>
      <div className="justify-center">
        <h1 className='text-center'>Deegle</h1>
        <ul className="text-sm font-medium text-center text-gray-500 dark:text-gray-400">
            <div className="flex">
              <li className="mr-2">
              <a href="#" className="inline-block py-3 px-4 text-white bg-blue-600 rounded-lg active" aria-current="page">Japanese</a>
              </li>
              <li>
              <a href="#" className="inline-block py-3 px-4 text-white bg-blue-600 rounded-lg active" aria-current="page">English</a>
              </li>
            </div>
        </ul>
          <div>
            <div className='flex-center px-10'>
              <UserTranslationText googleText = {inputText} translate = {translate}/>
            </div>
          </div>

        <div>
          <div className='flex-center mt-12'>
            <div className='flex ms:flex-center  justify-between'>
                 <textarea id="" className='border-2 mx-8 h-40 
                 border-rose-500 rounded-lg w-1/3 ms:flex-center ms:h-22' value={aftTranGoogle}>
                 </textarea>
                  <textarea id="" className='border-2	md:text-center mx-8 h-40 
                  border-violet-700 rounded-lg w-1/3' value={aftTranDeepl}>
                  </textarea>
            </div>

          </div>
           
            <div className='flex justify-between mx-auto container items-center'>
                 <button className='flex' onClick={goodGoogle}>
                  <FontAwesomeIcon icon={faThumbsUp} className="fa-2x" color='red'/>
                 </button>
                 <button className='flex' onClick={goodDeeple}>
                  <FontAwesomeIcon icon={faThumbsUp} className="fa-2x" color='red'/>
                  </button>
            </div>
        </div>

      </div>
      </main>      
      <footer className="">
      </footer>
    </div>
  );
}
export default Home
